WirtualnyDziennik/Models/Klasy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WirtualnyDziennik.Models
{
    public class Klasy
    {
        public virtual int id { get; set; }
        public virtual String nazwa { get; set; }
        public virtual Uzytkownicy Wychowawca { get; set; } // trzeba dodać jakieś ograniczenie, że tylko TYP UZYTKOWNIKA NAUCZYCIEL
    }
}

WirtualnyDziennik/Controllers/ClassesController.cs
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WirtualnyDziennik.Models;

namespace WirtualnyDziennik.Controllers
{
    public class ClassesController : Controller
    {
        // GET: Classes
        public ActionResult Index(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<Klasy> kl;

            using (ISession session = NhibernateSession.OpenSession())
            {
                kl = session.Query<Klasy>().Where(b => b.Wychowawca.id == id).ToList();
            }
            return View(kl);
        }

        public ActionResult ClassesStudentList(int id,int planlekcjiid)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            UserProfileSessionData upsd = Session["UserProfile"] as UserProfileSessionData;
            IList<Object[]> lista;
            IQuery s = null;
            using (ISession session = NhibernateSession.OpenSession())
            {

                s = session.CreateSQLQuery("select u.id, u.imie, u.nazwisko from uzytkownicy u, klasauczen ku, klasy k where u.id = ku.uzytkownik_id and ku.klasa_id = k.id and k.id = " + id);
                //U = session.Query<Uzytkownicy>().Where(c => c.id == session.Query<KlasaUczen>().Where(b => b.Klasy.id == session.Query<Klasy>().Where(a => a.Wychowawca.id == id).First().id).First().klasauczen_id).ToList();
                lista = s.List<Object[]>();
            }
            ViewData["planlekcjiid"] = planlekcjiid;
            return View(lista);
        }
        public ActionResult ListaLekcji(int id,int przedmiotid)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<PlanLekcji> lista;
            using (ISession session = NhibernateSession.OpenSession())
            {

                lista = session.Query<PlanLekcji>().Where(b => b.Klasa.id == id).Where(b=>b.Przedmiot.id==przedmiotid).ToList();
            }
            ViewData["przedmiotid"] = przedmiotid;
            ViewData["klasaid"] = id;
            return View(lista);
        }
   
    }
}

WirtualnyDziennik/Controllers/KlasyController.cs
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WirtualnyDziennik.Models;

namespace WirtualnyDziennik.Controllers
{
    public class KlasyController : Controller
    {
        public ActionResult Index(int id, int przedmiotid)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<Klasy> klasy = new List<Klasy>();
            IList<Decimal> Lista;
            ViewData["przedmiotid"] = przedmiotid;
            using (ISession session = NhibernateSession.OpenSession())
            {
                var s = session.CreateSQLQuery("select k.id from planlekcji pl,przedmioty p,klasy k where pl.planlekcji_id=p.id and k.id=pl.klasa_id and p.id=" + id);

                Lista = s.List<Decimal>();
                for (int i = 0; i < Lista.Count(); i++)
                {
                    Klasy k = new Klasy();
                    
                    k = session.Get<Klasy>(Convert.ToInt32(Lista.ElementAt(i)));
                    klasy.Add(k);
                }
            }
            
            return View(klasy);
        }

        public ActionResult IndexAdmin()
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<Klasy> klasy;
            List<String> nazwiska = new List<String>();
           
           
            using (ISession session = NhibernateSession.OpenSession())
            {
                klasy = session.Query<Klasy>().ToList();                
                for(int i = 0;i<klasy.Count();i++)
                {
                    nazwiska.Add(klasy[i].Wychowawca.nazwisko);
                }
            }

            return View(klasy);
        }

        public ActionResult Details(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Klasy klasy = new Klasy();
            using (ISession session = NhibernateSession.OpenSession())
            {
                klasy = session.Query<Klasy>().Where(b => b.id == id).FirstOrDefault();
            }

            return View(klasy);
        }

        public ActionResult Create()
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            using (ISession session = NhibernateSession.OpenSession())
             {
                List<Uzytkownicy> jakas = session.Query<Uzytkownicy>().Where(c => c.typu.id == 3).ToList();
                WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli = new List<System.Web.Mvc.SelectListItem>();
                for (int i = 0; i < jakas.Count(); i++)
                {
                    SelectListItem Item = new SelectListItem();
                    Item.Text = jakas[i].nazwa;
                    Item.Value = jakas[i].id.ToString();
                    Przedmioty.ListaDostepnychNauczycieli.Add(Item);
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult Create(Klasy model)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                using (ISession session = NhibernateSession.OpenSession())
                {

                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(model);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("IndexAdmin");
            }
            catch (Exception e)
            {
                return View();
            }
        }
        public ActionResult Add(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            using (ISession session = NhibernateSession.OpenSession())
            {
               
                List<Uzytkownicy> jakas = session.Query<Uzytkownicy>().Where(c => c.typu.id == 2).ToList();
                WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli = new List<System.Web.Mvc.SelectListItem>();
                for (int i = 0; i < jakas.Count(); i++)
                {
                    SelectListItem Item = new SelectListItem();
                    Item.Text = jakas[i].nazwisko;
                    Item.Value = jakas[i].id.ToString();
                    Przedmioty.ListaDostepnychNauczycieli.Add(Item);
                }
                ViewData["klasa"] = id;
                ViewBag.SubmitAction = "Save";
            }
            return View();
        }
[HttpPost]
 public ActionResult Add(KlasaUczen model)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            KlasaUczen ku= new KlasaUczen();
            
           
            try
            {
                using (ISession session = NhibernateSession.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(model);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("IndexAdmin");
            }
            catch (Exception e)
            {
                return View();
            }
        }

public ActionResult EditStudents(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Klasy klasy = new Klasy();
            using (ISession session = NhibernateSession.OpenSession())
            {
                List<KlasaUczen> klasauczen = session.Query<KlasaUczen>().Where(b => b.Klasa.id == id).ToList();
                IList<Object[]> s = session.CreateSQLQuery("select  u.* from uzytkownicy u,klasauczen where u.id=klasauczen.uzytkownik_id and klasauczen.klasa_id=" + id).List<Object[]>();
                List<Uzytkownicy> jakas = session.Query<Uzytkownicy>().Where(c => c.typu.id == 3).ToList();
                WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli = new List<System.Web.Mvc.SelectListItem>();
                for (int i = 0; i < s.Count(); i++)
                {
                    SelectListItem Item = new SelectListItem();
                    Item.Text = s[i][1].ToString();
                    Item.Value = s[i][0].ToString();
                    Przedmioty.ListaDostepnychNauczycieli.Add(Item);
                }
                klasy = session.Query<Klasy>().Where(b => b.id == id).FirstOrDefault();
            }
            ViewData["klasa"] = id;
            ViewBag.SubmitAction = "Save";
            return View(klasy);
        }

        public ActionResult Edit(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Klasy klasy = new Klasy();
            using (ISession session = NhibernateSession.OpenSession())
            {
                List<Uzytkownicy> jakas = session.Query<Uzytkownicy>().Where(c => c.typu.id == 3).ToList();
                WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli = new List<System.Web.Mvc.SelectListItem>();
                for (int i = 0; i < jakas.Count(); i++)
                {
                    SelectListItem Item = new SelectListItem();
                    Item.Text = jakas[i].nazwa;
                    Item.Value = jakas[i].id.ToString();
                    Przedmioty.ListaDostepnychNauczycieli.Add(Item);
                }
                klasy = session.Query<Klasy>().Where(b => b.id == id).FirstOrDefault();
            }

            ViewBag.SubmitAction = "Save";
            return View(klasy);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                Klasy klasy = new Klasy();
                klasy.id = id;
                klasy.nazwa = collection["Nazwa"].ToString();
                using (ISession session = NhibernateSession.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.SaveOrUpdate(klasy);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Klasy klasy = new Klasy();
            using (ISession session = NhibernateSession.OpenSession())
            {
                klasy = session.Query<Klasy>().Where(b => b.id == id).FirstOrDefault();
            }
            ViewBag.SubmitAction = "Confirm delete";
            return View("Edit", klasy);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {

WirtualnyDziennik/Views/Klasy/Add.cshtml
@model WirtualnyDziennik.Models.KlasaUczen

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            
            <div class="col-md-10">
                @Html.Label("Wybierz uzytkownika")
                <br />
                @Html.DropDownListFor(model => model.Uzytkownik.id, WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uzytkownik.id, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Klasa.id,new {@Value=ViewData["klasa"]})
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@ViewBag.SubmitAction class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/Klasy/Create.cshtml
@model WirtualnyDziennik.Models.Klasy

@{
    ViewBag.Title = "Create";
}

<h2>Creating new type</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
        </div>
    </div>
    @Html.LabelFor(model => model.Wychowawca, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.Wychowawca.id, WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Wychowawca, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/Klasy/Details.cshtml
@model WirtualnyDziennik.Models.Klasy

@{
    ViewBag.Title = "Book";
}

<h2>Book</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WirtualnyDziennik/Views/Klasy/Edit.cshtml
@model WirtualnyDziennik.Models.Klasy

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.Wychowawca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Wychowawca.id, WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wychowawca, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@ViewBag.SubmitAction class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/Klasy/EditStudents.cshtml
@model WirtualnyDziennik.Models.Klasy

@{
    ViewBag.Title = "Create";
}

<h2>Creating new type</h2>

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.nazwa)
        </div>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Imię")
            </th>
            <th>
                @Html.DisplayName("Nazwisko")
            </th>
            <th></th>
        </tr>

        @foreach (var item in WirtualnyDziennik.Models.Przedmioty.ListaDostepnychNauczycieli)
        {
        <tr>
            <td>
                @Html.DisplayName(item.Value)
            </td>
            <td>
                @Html.DisplayName(item.Text)
            </td>
            <td>
                <button onclick="location.href='@Url.Action("DeleteStudent", "KlasaUczen", new { id = item.Value })'" type="button" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Usuń </button>
            </td>
        </tr>
        }
    </table>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button onclick="location.href='@Url.Action("Add", "Klasy", new { id =ViewData["Klasa"] } )'" type="submit" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Dodaj ucznia </button>
        </div>
    </div>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/Klasy/Index.cshtml
@model IEnumerable<WirtualnyDziennik.Models.Klasy>

@{
    var Konto = this.Session["UserProfile"] as WirtualnyDziennik.Models.UserProfileSessionData;

    if (Konto.Typ == "ADMIN") { 
<p>
    <button onclick="location.href='@Url.Action("Create", "TypUzytkownika")'" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj Klasę</button>
</p>
    }
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nazwa)
            </td>
            @if (Konto.Typ == "NAUCZYCIEL")
            {
                <td>
                    <button onclick="location.href='@Url.Action("ListaLekcji", "Classes", new { id = item.id ,przedmiotid=ViewData["przedmiotid"]} )'" type="button" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edytuj </button>
                </td>
            }
        </tr>
    }

</table>

WirtualnyDziennik/Views/Klasy/IndexAdmin.cshtml
@model IEnumerable<WirtualnyDziennik.Models.Klasy>
<p>
    <button onclick="location.href='@Url.Action("Create", "Klasy")'" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nowa Klasa</button>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <!--<th>
       // @Html.DisplayNameFor(model => model.Wychowawca)
    </th>-->
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Wychowawca.nazwisko)
        </td>
        <td>
            <button onclick="location.href='@Url.Action("Edit", "Klasy", new { id = item.id } )'" type="button" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edytuj </button>
            <button onclick="location.href='@Url.Action("EditStudents", "Klasy", new { id = item.id })'" type="button" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Przypisz Uczniów </button>
            <button onclick="location.href='@Url.Action("Index", "PlanLekcji", new { id = item.id })'" type="button" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Przypisz Uczniów </button>
            <button onclick="location.href='@Url.Action("Delete", "Klasy", new { id = item.id })'" type="button" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Usuń </button>
        </td>

    </tr>
    }

</table>