WirtualnyDziennik/Models/Uzytkownicy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WirtualnyDziennik.Models
{
    public class Uzytkownicy
    {
        public virtual int id { get; set; }
        public virtual String nazwa { get; set; }
        public virtual String haslo { get; set; }
        public virtual String email { get; set; }
        public virtual UInt64 pesel { get; set; }
        public virtual String nazwisko { get; set; }
        public virtual String imie { get; set; }
        public virtual int kod { get; set; }
        public virtual String miasto { get; set; }
        public virtual String ulica { get; set; }
        public virtual int numer { get; set; }
        public virtual int numer_m { get; set; }
        public virtual int miejsce_kod { get; set; }
        public virtual String miejsce_ur { get; set; }
        public virtual DateTime data_ur{ get; set; }
        public virtual TypUzytkownika typu { get; set; }

        public static List<System.Web.Mvc.SelectListItem> ListaDostepnych { get; set; }
    }
}

WirtualnyDziennik/Controllers/UzytkownicyController.cs
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WirtualnyDziennik.Models;

namespace WirtualnyDziennik.Controllers
{
    public class UzytkownicyController : Controller
    {
        public ActionResult Index()
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<Uzytkownicy> Uzytkownicy;

            using (ISession session = NhibernateSession.OpenSession())
            {
                Uzytkownicy = session.Query<Uzytkownicy>().ToList();
            }

            return View(Uzytkownicy);
        }

        public ActionResult Details(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Uzytkownicy Uzytkownicy = new Uzytkownicy();
            using (ISession session = NhibernateSession.OpenSession())
            {
                Uzytkownicy = session.Query<Uzytkownicy>().Where(b => b.id == id).FirstOrDefault();
            }

            return View(Uzytkownicy);
        }

        public ActionResult Create()
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            using (ISession session = NhibernateSession.OpenSession())
            {
                List<TypUzytkownika> jakas = session.Query<TypUzytkownika>().ToList();
                Uzytkownicy.ListaDostepnych = new List<System.Web.Mvc.SelectListItem>();
                for (int i = 0; i < jakas.Count(); i++)
                {
                    SelectListItem Item = new SelectListItem();
                    Item.Text = jakas[i].nazwa;
                    Item.Value = jakas[i].id.ToString();
                    Uzytkownicy.ListaDostepnych.Add(Item);
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(Uzytkownicy model)
                  {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                
                using (ISession session = NhibernateSession.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(model);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
             catch (Exception e)
            {
                ViewBag.Message = e.Message+"##ZRODLO##"+e.Source+"##DALEJ##"+e.InnerException;
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Uzytkownicy Uzytkownicy = new Uzytkownicy();
            using (ISession session = NhibernateSession.OpenSession())
            {
                List<TypUzytkownika> jakas = session.Query<TypUzytkownika>().ToList();
                Uzytkownicy.ListaDostepnych = new List<System.Web.Mvc.SelectListItem>();
                for (int i = 0; i < jakas.Count(); i++)
                {
                    SelectListItem Item = new SelectListItem();
                    Item.Text = jakas[i].nazwa;
                    Item.Value = jakas[i].id.ToString();
                    Uzytkownicy.ListaDostepnych.Add(Item);
                }
                Uzytkownicy = session.Query<Uzytkownicy>().Where(b => b.id == id).FirstOrDefault();
            }
            
            ViewBag.SubmitAction = "Save";
            return View(Uzytkownicy);
        }

        [HttpPost]
        public ActionResult Edit(int id, Uzytkownicy model)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                using (ISession session = NhibernateSession.OpenSession())
                {
                    Uzytkownicy Uzytkownicy = session.Get<Uzytkownicy>(id);
                        if(model.haslo!=null) Uzytkownicy.haslo = model.haslo;
                        if(model.pesel!=0) Uzytkownicy.pesel = model.pesel;
                        if (model.nazwisko != null) Uzytkownicy.nazwisko = model.nazwisko;
                    if (model.imie != null) Uzytkownicy.imie = model.imie;
                    if (model.kod != 0) Uzytkownicy.kod = model.kod;
                    if (model.miasto != null) Uzytkownicy.miasto = model.miasto;
                    if (model.ulica != null) Uzytkownicy.ulica = model.ulica;
                    if (model.numer != 0) Uzytkownicy.numer = model.numer;
                    if (model.numer_m != 0) Uzytkownicy.numer_m = model.numer_m;
                    if (model.miejsce_kod != 0) Uzytkownicy.miejsce_kod = model.miejsce_kod;
                    if (model.miejsce_ur != null) Uzytkownicy.miejsce_ur = model.miejsce_ur;
                    if (model.data_ur != null) Uzytkownicy.data_ur = model.data_ur;
                        if(Uzytkownicy.typu.id==1) Uzytkownicy.typu = (TypUzytkownika)session.Load("TypUzytkownika",model.typu.id);
                    using (ITransaction transaction = session.BeginTransaction())
                    {

                        session.SaveOrUpdate(Uzytkownicy);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Uzytkownicy Uzytkownicy = new Uzytkownicy();
            List<Uzytkownicy> Lista = new List<Uzytkownicy>();
            using (ISession session = NhibernateSession.OpenSession())
            {
              //  List<TypUzytkownika> jakas = session.Query<TypUzytkownika>().ToList();
             //   Uzytkownicy.ListaDostepnych = new List<System.Web.Mvc.SelectListItem>();
             //   for (int i = 0; i < jakas.Count(); i++)
             //   {
            //        SelectListItem Item = new SelectListItem();
            //        Item.Text = jakas[i].nazwa;
            //        Item.Value = jakas[i].id.ToString();
           //         Uzytkownicy.ListaDostepnych.Add(Item);
           //     }
                Uzytkownicy = session.Query<Uzytkownicy>().Where(b => b.id == id).FirstOrDefault();
                using (ITransaction Transaction = session.BeginTransaction())
                {
                    session.Delete(Uzytkownicy);
                    Transaction.Commit();
                }
                Lista = session.Query<Uzytkownicy>().ToList();
            }
            //ViewBag.SubmitAction = "Confirm delete";
            return View("Index");
        }

       /* [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (ISession session = NhibernateSession.OpenSession())
                {
                    Uzytkownicy Uzytkownicy = session.Get<Uzytkownicy>(id);

                    using (ITransaction trans = session.BeginTransaction())
                    {
                        session.Delete(Uzytkownicy);
                        trans.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }*/
    }
}

WirtualnyDziennik/Views/Uzytkownicy/Create.cshtml
@model WirtualnyDziennik.Models.Uzytkownicy

@{
    ViewBag.Title = "Create";
}

<h2>Creating new type</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.haslo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.haslo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.haslo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imie, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pesel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pesel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pesel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miasto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miasto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miasto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ulica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numer, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.numer_m, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numer_m, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numer_m, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.data_ur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_ur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_ur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miejsce_ur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miejsce_ur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miejsce_ur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miejsce_kod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miejsce_kod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miejsce_kod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.typu.id, WirtualnyDziennik.Models.Uzytkownicy.ListaDostepnych, new { htmlAttributes = new { @class = "form-control" } })
                 
                @Html.ValidationMessageFor(model => model.typu, "", new { @class = "text-danger" })
            </div>
        </div>
       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <p>@ViewBag.Message</p>

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/Uzytkownicy/Details.cshtml
@model WirtualnyDziennik.Models.Uzytkownicy

@{
    ViewBag.Title = "Book";
}

<h2>Book</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WirtualnyDziennik/Views/Uzytkownicy/Edit.cshtml
@model WirtualnyDziennik.Models.Uzytkownicy

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.haslo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.haslo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.haslo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imie, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pesel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pesel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pesel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miasto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miasto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miasto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ulica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numer, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.numer_m, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numer_m, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numer_m, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.data_ur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_ur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_ur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miejsce_ur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miejsce_ur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miejsce_ur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miejsce_kod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miejsce_kod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miejsce_kod, "", new { @class = "text-danger" })
            </div>
        </div>

        @{var Konto = this.Session["UserProfile"] as WirtualnyDziennik.Models.UserProfileSessionData; }
        @if (this.Session["UserProfile"]!=null)
        {
            if (Konto.Typ == "ADMIN")
            {
        <div class="form-group">
            @Html.LabelFor(model => model.typu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.typu.id, WirtualnyDziennik.Models.Uzytkownicy.ListaDostepnych, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.typu, "", new { @class = "text-danger" })
            </div>
        </div>
            }
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@ViewBag.SubmitAction class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/Uzytkownicy/Index.cshtml
@model IEnumerable<WirtualnyDziennik.Models.Uzytkownicy>
<p>
    <button onclick="location.href='@Url.Action("Create", "Uzytkownicy")'" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nowy Użytkownik</button>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nazwa)
            </td>
            <td>
                <button onclick="location.href='@Url.Action("Edit", "Uzytkownicy", new { id = item.id } )'" type="button" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit </button>
                <button onclick="location.href='@Url.Action("Details", "Uzytkownicy", new { id = item.id })'" type="button" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Details </button>
                <button onclick="location.href='@Url.Action("Delete", "Uzytkownicy", new { id = item.id })'" type="button" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Delete </button>
            </td>
        </tr>
    }

</table>