WirtualnyDziennik/Models/TypTresci.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WirtualnyDziennik.Models
{
    public class TypTresci
    {
        public virtual int id { get; set; }
        public virtual String nazwa { get; set; }
        public virtual IList<TypTresci> Costam { get; set; }

        public static List<System.Web.Mvc.SelectListItem> ListaDostepnych { get; set; }
    }
}

WirtualnyDziennik/Controllers/TypTresciController.cs
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WirtualnyDziennik.Models;

namespace WirtualnyDziennik.Controllers
{
    public class TypTresciController : Controller
    {
         public ActionResult Index()
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            IList<TypTresci> TTresci;
            
            using (ISession session = NhibernateSession.OpenSession())  
            {
                TTresci = session.Query<TypTresci>().ToList(); 
            }
            return View(TTresci);
        }

        public ActionResult Details(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TypTresci TTresc = new TypTresci();
            using (ISession session = NhibernateSession.OpenSession())
            {
                TTresc = session.Query<TypTresci>().Where(b => b.id == id).FirstOrDefault();
            }

            return View(TTresc);
        }

        public ActionResult Create()
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            /* TypTresci TTresc = new TypTresci();
             using (ISession session = NhibernateSession.OpenSession())
             {

                 using (ITransaction transaction = session.BeginTransaction())   
                 {
                     session.Save(TTresc);
                     transaction.Commit();  
                 }
             }*/
            return View();
        }

        [HttpPost]
        public ActionResult Create(String nazwa)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                TypTresci TTresc = new TypTresci();                                     
                TTresc.nazwa = nazwa;
                using (ISession session = NhibernateSession.OpenSession())
                {

                    using (ITransaction transaction = session.BeginTransaction()) 
                    {
                        session.Save(TTresc);
                        transaction.Commit();  
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TypTresci TTresc = new TypTresci();
            using (ISession session = NhibernateSession.OpenSession())
            {
                TTresc = session.Query<TypTresci>().Where(b => b.id == id).FirstOrDefault();
            }

            ViewBag.SubmitAction = "Save";
            return View(TTresc);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                TypTresci TTresc = new TypTresci();
                TTresc.id = id;
                TTresc.nazwa = collection["Nazwa"].ToString();
                using (ISession session = NhibernateSession.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.SaveOrUpdate(TTresc);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TypTresci TTresc = new TypTresci();
            using (ISession session = NhibernateSession.OpenSession())
            {
                TTresc = session.Query<TypTresci>().Where(b => b.id == id).FirstOrDefault();
            }
            ViewBag.SubmitAction = "Confirm delete";
            return View("Edit", TTresc);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (this.Session["UserProfile"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                using (ISession session = NhibernateSession.OpenSession())
                {
                    TypTresci TTresc = session.Get<TypTresci>(id);

                    using (ITransaction trans = session.BeginTransaction())
                    {
                        session.Delete(TTresc);
                        trans.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message + "##ZRODLO##" + e.Source + "##DALEJ##" + e.InnerException;
                return RedirectToAction("Index");
            }
        }
    }
}

WirtualnyDziennik/Views/TypTresci/Create.cshtml
@model WirtualnyDziennik.Models.TypTresci

@{
    ViewBag.Title = "Create";
}

<h2>Creating new type</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/TypTresci/Details.cshtml
@model WirtualnyDziennik.Models.TypTresci

@{
    ViewBag.Title = "Book";
}

<h2>Book</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NAZWA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAZWA)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WirtualnyDziennik/Views/TypTresci/Edit.cshtml
@model WirtualnyDziennik.Models.TypTresci

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NAZWA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAZWA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAZWA, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@ViewBag.SubmitAction class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WirtualnyDziennik/Views/TypTresci/Index.cshtml
@model IEnumerable<WirtualnyDziennik.Models.TypTresci>
<p>
    <button onclick="location.href='@Url.Action("Create", "TypTresci")'" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nowy Typ</button>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nazwa)
            </td>
            <td>
                <button onclick="location.href='@Url.Action("Edit", "TypTresci", new { id = item.id } )'" type="button" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit </button>
                <button onclick="location.href='@Url.Action("Details", "TypTresci", new { id = item.id })'" type="button" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Details </button>
                <button onclick="location.href='@Url.Action("Delete", "TypTresci", new { id = item.id })'" type="button" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Delete </button>
            </td>
           
        </tr>
    }

</table>